services:
  lrg-local:
    container_name: lrg
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src/lrg:/app
    env_file:
      - docker-compose.env
    ports:
      - 8080:8080
    depends_on:
      - db
    entrypoint: ["gunicorn", "lrg.wsgi:application", "--bind", "0.0.0.0:8080"]
  db:
    image: postgres
    container_name: postgres_local
    restart: always
    env_file:
      - docker-compose-pg.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: