# Generated by Django 5.1.6 on 2025-02-18 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        ('homepage', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communities_owned', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='community',
            name='staff',
            field=models.ManyToManyField(related_name='communities_as_staff', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='community',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.contactinfo'),
        ),
        migrations.AddField(
            model_name='season',
            name='banner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.externalimage'),
        ),
        migrations.AddField(
            model_name='season',
            name='cast',
            field=models.ManyToManyField(related_name='seasons_as_cast', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='season',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community'),
        ),
        migrations.AddField(
            model_name='season',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.location'),
        ),
        migrations.AddField(
            model_name='season',
            name='schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.schedule'),
        ),
        migrations.AddField(
            model_name='season',
            name='staff',
            field=models.ManyToManyField(related_name='seasons_as_staff', to='profiles.profile'),
        ),
    ]
