# Generated by Django 5.1.6 on 2025-02-23 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('account_status', models.CharField(choices=[('Active', 'Active'), ('Banned', 'Banned'), ('Suspended', 'Suspended'), ('Muted', 'Muted'), ('Under Review', 'Under Review')], max_length=256)),
                ('auth_source', models.CharField(choices=[('Internal', 'Internal')], default='Internal', max_length=256)),
                ('pronouns', models.CharField(blank=True, max_length=256, null=True)),
                ('icon', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.externalimage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
