# Generated by Django 5.1.6 on 2025-02-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_size_url', models.CharField()),
                ('description', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, null=True)),
                ('country_short', models.CharField(blank=True, null=True)),
                ('region', models.CharField(blank=True, null=True)),
                ('region_short', models.CharField(blank=True, null=True)),
                ('city', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SafeGet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
